import{test,expect,type Page}from'@playwright/test';
test('QT6 publicar, guardar, evaluar dos intentos y consultar libro',async({page,browser})=>{
 test.skip(process.env.E2E_ACADEMIC!=='1','Requiere Go/PostgreSQL sintético');test.setTimeout(120_000);const origin=process.env.E2E_BASE_URL??'http://localhost:4321';
 async function login(p:Page,user:string){await p.goto('/login');await p.getByLabel('Tu usuario').fill(user);await p.getByLabel('Tu contraseña').fill(user==='profe'?process.env.E2E_TEACHER_PASSWORD!:process.env.E2E_STUDENT_PASSWORD!);await p.getByRole('button',{name:'Entrar a mi aventura'}).click();await expect(p).toHaveURL(user==='profe'?/\/teacher$/:/\/courses$/);}
 await login(page,'profe');const course=(await(await page.request.get('/api/v1/teacher/courses')).json()).items[0];const stamp=Date.now();
 const base={name:`Ave ${stamp}`,type:'single_choice',prompt:'Elige el animal que vuela.',options:['Pájaro','Pez'],correctChoices:[0],acceptedAnswers:[],caseSensitive:false,explanation:'Solución privada del cuestionario.'};
 const qr=await page.request.post(`/api/v1/teacher/courses/${course.id}/questions`,{headers:{Origin:origin},data:base});expect(qr.status()).toBe(201);const q1=await qr.json();
 const sr=await page.request.post(`/api/v1/teacher/courses/${course.id}/questions`,{headers:{Origin:origin},data:{...base,name:`Palabra ${stamp}`,type:'short_answer',prompt:'Escribe bosque.',options:[],correctChoices:[],acceptedAnswers:['bosque']}});expect(sr.status()).toBe(201);const q2=await sr.json();
 await page.goto(`/teacher/courses/${course.id}`);await page.getByLabel('Tipo de actividad').selectOption('quiz');await page.getByLabel('Título',{exact:true}).fill(`Cuestionario ${stamp}`);await page.getByLabel('Contenido o instrucciones').fill('Responde con calma. Guarda antes de enviar.');await page.getByRole('button',{name:'Guardar borrador',exact:true}).click();await expect(page).toHaveURL(/\/teacher\/activities\/\d+$/);
 const activityId=page.url().split('/').at(-1)!;await expect(page.getByRole('button',{name:'Publicar actividad'})).toBeDisabled();await page.getByRole('link',{name:'Configurar cuestionario',exact:true}).click();
 await page.getByLabel('Máximo de intentos',{exact:true}).fill('2');await page.getByLabel('Nota que cuenta en el libro').selectOption('highest');await page.getByLabel('Cuándo mostrar las soluciones').selectOption('never');
 await page.getByLabel(`${q1.content.name} · versión 1`,{exact:true}).check();await page.getByLabel(`${q2.content.name} · versión 1`,{exact:true}).check();await page.getByLabel(`Peso de ${q2.content.name}`,{exact:true}).fill('3');
 await page.getByRole('button',{name:'Guardar configuración del cuestionario'}).click();await expect(page.locator('quiz-composer')).toHaveAttribute('data-version','2');await page.getByRole('link',{name:'Volver a la actividad'}).click();await page.getByRole('button',{name:'Publicar actividad'}).click();await expect(page.getByText('Última versión publicada: 2.',{exact:false})).toBeVisible();
 const activity=await(await page.request.get(`/api/v1/teacher/activities/${activityId}`)).json();const textIndex=activity.quizConfig.items.findIndex((i:{questionId:number})=>i.questionId===q2.id)+1;
 const context=await browser.newContext({viewport:{width:768,height:1024},reducedMotion:'reduce'});const student=await context.newPage();
 try{
  await login(student,'luna');const before=await(await student.request.get('/api/v1/me/progress')).json();await student.goto(`/lessons/${activity.lessonId}`);await student.getByRole('button',{name:'Comenzar intento 1',exact:true}).click();await expect(student.getByRole('heading',{name:'Intento 1',exact:true})).toBeVisible();
  const secretCheck=await(await student.request.get(`/api/v1/lessons/${activity.lessonId}/quiz`)).text();expect(secretCheck).not.toContain('correctChoices');expect(secretCheck).not.toContain('acceptedAnswers');expect(secretCheck).not.toContain('Solución privada');
  await student.getByLabel('Pájaro',{exact:true}).check();await student.getByLabel(`Respuesta a la pregunta ${textIndex}`,{exact:true}).fill('incorrecto');await expect(student.getByRole('button',{name:'Enviar cuestionario',exact:true})).toBeDisabled();
  await student.route('**/api/v1/lessons/*/quiz/attempts/*',route=>route.abort());await student.getByRole('button',{name:'Guardar respuestas',exact:true}).click();await expect(student.locator('quiz-attempt [data-status]')).toContainText('Tus respuestas permanecen');await expect(student.getByLabel(`Respuesta a la pregunta ${textIndex}`,{exact:true})).toHaveValue('incorrecto');await student.unroute('**/api/v1/lessons/*/quiz/attempts/*');
  await student.getByRole('button',{name:'Guardar respuestas',exact:true}).click();await expect(student.locator('quiz-attempt [data-status]')).toContainText('Respuestas guardadas');
  const changedResponse=await page.request.put(`/api/v1/teacher/activities/${activityId}`,{headers:{Origin:origin},data:{version:activity.version,title:activity.title,description:activity.description,body:'Instrucciones nuevas para los siguientes intentos.'}});expect(changedResponse.ok()).toBeTruthy();const changed=await changedResponse.json();expect((await page.request.post(`/api/v1/teacher/activities/${activityId}/publish`,{headers:{Origin:origin},data:{version:changed.version}})).ok()).toBeTruthy();
  await student.reload();await expect(student.getByLabel('Pájaro',{exact:true})).toBeChecked();await expect(student.getByLabel(`Respuesta a la pregunta ${textIndex}`,{exact:true})).toHaveValue('incorrecto');await expect(student.getByText('Las instrucciones cambiaron.',{exact:false})).toBeVisible();await student.locator('quiz-attempt summary').click();await expect(student.getByText('Responde con calma. Guarda antes de enviar.',{exact:true})).toBeVisible();
  await student.getByRole('button',{name:'Enviar cuestionario',exact:true}).click();await expect(student.getByText('Resultado de este intento: 25 / 100',{exact:true})).toBeVisible();await expect(student.getByRole('heading',{name:/Revisión de la pregunta/})).toHaveCount(0);
  await student.getByRole('button',{name:'Comenzar intento 2',exact:true}).click();await expect(student.getByRole('heading',{name:'Intento 2',exact:true})).toBeVisible();await student.getByLabel('Pájaro',{exact:true}).check();await student.getByLabel(`Respuesta a la pregunta ${textIndex}`,{exact:true}).fill('BOSQUE');await student.getByRole('button',{name:'Guardar respuestas',exact:true}).click();await expect(student.locator('quiz-attempt [data-status]')).toContainText('Respuestas guardadas');await student.getByRole('button',{name:'Enviar cuestionario',exact:true}).click();await expect(student.getByText('Resultado de este intento: 100 / 100',{exact:true})).toBeVisible();await expect(student.getByText('Ya usaste los intentos disponibles.',{exact:false})).toBeVisible();
  const state=await(await student.request.get(`/api/v1/lessons/${activity.lessonId}/quiz`)).json();const after=await(await student.request.get('/api/v1/me/progress')).json();expect(after.xp).toBe(before.xp);expect(after.gems).toBe(before.gems);expect(after.stars).toBe(before.stars);expect(after.completed).toBe(before.completed+1);
  await expect(student.getByLabel('Tu progreso')).toContainText('Luna');await student.screenshot({path:'../docs/screenshots/quiz-student-tablet.png',fullPage:true,animations:'disabled'});
  await page.goto(`/teacher/activities/${activityId}/quiz-results`);await expect(page.getByRole('link',{name:'Revisar intento 1 de Luna',exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Revisar intento 2 de Luna',exact:true})).toBeVisible();
  let columnPage=1;let found=false;do{const book=await(await page.request.get(`/api/v1/teacher/courses/${course.id}/gradebook?activityPage=${columnPage}`)).json();found=book.activities.some((a:{activityId:number})=>a.activityId===Number(activityId));if(found){const cell=book.rows.find((r:{alias:string})=>r.alias==='Luna').cells.find((c:{activityId:number})=>c.activityId===Number(activityId));expect(cell.score).toBe(100);expect(cell.quizAttemptId).toBe(state.attempt.id);expect(cell.submissionId).toBeNull();break;}if(columnPage*10>=book.totalActivities)break;columnPage++;}while(columnPage<100);expect(found).toBeTruthy();
  await page.goto(`/teacher/courses/${course.id}/gradebook?activityPage=${columnPage}`);await page.locator(`a[href="/teacher/quiz-attempts/${state.attempt.id}"]`).click();await expect(page.getByText('Resultado de este intento: 100 / 100',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:/Revisión de la pregunta/})).toHaveCount(2);await expect(page.getByRole('button',{name:'Enviar cuestionario'})).toHaveCount(0);await page.screenshot({path:'../docs/screenshots/quiz-teacher-tablet.png',fullPage:true,animations:'disabled'});
 }finally{await context.close();}
});
